INSERT INTO LANGUAGE (ID, NAME, DESIGNED, YEAR, VERSION) VALUES (1, 'Kotlin', 'Jetbrains', 2013, '1.3.61');
INSERT INTO LANGUAGE (ID, NAME, DESIGNED, YEAR, VERSION) VALUES (2, 'Java', 'James Gosling', 1995, 'Java SE 14');
